create table if not exists public.paper_autonomous_allocation_proposal_reports (
    report_sha256 text primary key,
    generated_at timestamptz not null,
    config_version text not null,
    proposal_status text not null,
    recommended_next_step text not null,
    reason_codes_json jsonb not null,
    reason_code_counts_json jsonb not null,
    screening_gate_generated_at timestamptz not null,
    screening_gate_config_version text not null,
    screening_gate_status text not null,
    screening_gate_recommended_next_step text not null,
    queue_risk_generated_at timestamptz not null,
    queue_risk_config_version text not null,
    queue_risk_status text not null,
    queue_risk_recommended_next_step text not null,
    source_queue_report_count integer not null,
    source_queue_ready_count integer not null,
    source_queue_watch_count integer not null,
    source_queue_blocked_count integer not null,
    allocation_config_version text not null,
    allocation_generated_at timestamptz not null,
    allocation_input_count integer not null,
    allocation_row_count integer not null,
    allocation_allocated_count integer not null,
    allocation_capped_count integer not null,
    allocation_no_budget_count integer not null,
    allocation_non_recommend_count integer not null,
    allocation_skipped_count integer not null,
    allocation_total_requested_paper_notional numeric(38, 6) not null,
    allocation_total_allocated_paper_notional numeric(38, 6) not null,
    allocation_remaining_paper_budget numeric(38, 6) not null,
    allocation_total_paper_budget numeric(38, 6) not null,
    allocation_max_paper_notional_per_market numeric(38, 6) not null,
    allocation_max_paper_notional_per_event numeric(38, 6) not null,
    allocation_max_paper_notional_per_theme numeric(38, 6) not null,
    allocation_max_paper_notional_per_correlation_group numeric(38, 6) not null,
    allocation_rows_json jsonb not null,
    payload_json jsonb not null,
    paper_only boolean not null default true,
    report_only boolean not null default true,
    readonly boolean not null default true,
    inserted_at timestamptz not null default now(),
    check (report_sha256 ~ '^[a-f0-9]{64}$'),
    check (proposal_status in ('pass', 'watch', 'blocked')),
    check (screening_gate_status in ('pass', 'watch', 'blocked')),
    check (queue_risk_status in ('pass', 'watch', 'blocked')),
    check (recommended_next_step = case proposal_status when 'pass' then 'review_paper_autonomous_allocation_proposal' when 'watch' then 'hold_paper_autonomous_allocation_proposal' when 'blocked' then 'block_paper_autonomous_allocation_proposal' end),
    check (jsonb_typeof(reason_codes_json) = 'array'),
    check (jsonb_typeof(reason_code_counts_json) = 'array'),
    check (jsonb_typeof(allocation_rows_json) = 'array'),
    check (jsonb_typeof(payload_json) = 'object'),
    check (source_queue_report_count >= 0),
    check (source_queue_ready_count >= 0),
    check (source_queue_watch_count >= 0),
    check (source_queue_blocked_count >= 0),
    check (allocation_input_count >= 0),
    check (allocation_row_count >= 0),
    check (allocation_allocated_count >= 0),
    check (allocation_capped_count >= 0),
    check (allocation_no_budget_count >= 0),
    check (allocation_non_recommend_count >= 0),
    check (allocation_skipped_count >= 0),
    check (allocation_total_requested_paper_notional >= 0),
    check (allocation_total_allocated_paper_notional >= 0),
    check (allocation_remaining_paper_budget >= 0),
    check (allocation_total_paper_budget >= 0),
    check (allocation_max_paper_notional_per_market >= 0),
    check (allocation_max_paper_notional_per_event >= 0),
    check (allocation_max_paper_notional_per_theme >= 0),
    check (allocation_max_paper_notional_per_correlation_group >= 0),
    check (allocation_row_count = allocation_allocated_count + allocation_capped_count + allocation_no_budget_count + allocation_non_recommend_count + allocation_skipped_count),
    check (jsonb_array_length(allocation_rows_json) = allocation_row_count),
    check (payload_json ? 'generated_at' and jsonb_typeof(payload_json -> 'generated_at') = 'string' and (payload_json ->> 'generated_at')::timestamptz = generated_at),
    check (payload_json ? 'config_version' and jsonb_typeof(payload_json -> 'config_version') = 'string' and payload_json ->> 'config_version' = config_version),
    check (payload_json ? 'proposal_status' and jsonb_typeof(payload_json -> 'proposal_status') = 'string' and payload_json ->> 'proposal_status' = proposal_status),
    check (payload_json ? 'recommended_next_step' and jsonb_typeof(payload_json -> 'recommended_next_step') = 'string' and payload_json ->> 'recommended_next_step' = recommended_next_step),
    check (payload_json ? 'reason_codes' and jsonb_typeof(payload_json -> 'reason_codes') = 'array' and payload_json -> 'reason_codes' = reason_codes_json),
    check (payload_json ? 'reason_code_counts' and jsonb_typeof(payload_json -> 'reason_code_counts') = 'array' and payload_json -> 'reason_code_counts' = reason_code_counts_json),
    check (payload_json ? 'allocation_report' and jsonb_typeof(payload_json -> 'allocation_report') = 'object'),
    check (payload_json -> 'allocation_report' ? 'rows' and jsonb_typeof(payload_json -> 'allocation_report' -> 'rows') = 'array' and payload_json -> 'allocation_report' -> 'rows' = allocation_rows_json),
    check (payload_json ? 'paper_only' and payload_json -> 'paper_only' = 'true'::jsonb),
    check (payload_json ? 'report_only' and payload_json -> 'report_only' = 'true'::jsonb),
    check (payload_json ? 'readonly' and payload_json -> 'readonly' = 'true'::jsonb),
    check (paper_only is true),
    check (report_only is true),
    check (readonly is true)
);

create index if not exists idx_paapr_generated_at on public.paper_autonomous_allocation_proposal_reports (generated_at desc);
create index if not exists idx_paapr_status_generated on public.paper_autonomous_allocation_proposal_reports (proposal_status, generated_at desc);
create index if not exists idx_paapr_config_generated on public.paper_autonomous_allocation_proposal_reports (config_version, generated_at desc);
create index if not exists idx_paapr_screening_status_generated on public.paper_autonomous_allocation_proposal_reports (screening_gate_status, generated_at desc);
create index if not exists idx_paapr_allocation_config_generated on public.paper_autonomous_allocation_proposal_reports (allocation_config_version, generated_at desc);
create index if not exists idx_paapr_reason_codes_json on public.paper_autonomous_allocation_proposal_reports using gin (reason_codes_json);
create index if not exists idx_paapr_reason_counts_json on public.paper_autonomous_allocation_proposal_reports using gin (reason_code_counts_json);
create index if not exists idx_paapr_allocation_rows_json on public.paper_autonomous_allocation_proposal_reports using gin (allocation_rows_json);
create index if not exists idx_paapr_payload_json on public.paper_autonomous_allocation_proposal_reports using gin (payload_json);
