create table if not exists public.paper_autonomous_allocation_proposal_db_history_health_reports (
    report_sha256 text primary key,
    generated_at timestamptz not null,
    config_version text not null,
    health_status text not null,
    recommended_next_step text not null,
    history_report_count integer not null,
    pass_report_count integer not null,
    watch_report_count integer not null,
    blocked_report_count integer not null,
    latest_history_status text,
    latest_proposal_status text,
    latest_allocated_count integer,
    latest_total_allocated_paper_notional numeric(38, 6),
    max_source_age_seconds integer,
    latest_source_age_seconds integer,
    duplicate_latest_report_generated_at_count integer not null,
    reason_code_counts_json jsonb not null,
    reason_codes_json jsonb not null,
    payload_json jsonb not null,
    paper_only boolean not null default true,
    report_only boolean not null default true,
    readonly boolean not null default true,
    inserted_at timestamptz not null default now(),
    check (report_sha256 ~ '^[a-f0-9]{64}$'),
    check (health_status in ('pass', 'watch', 'blocked')),
    check (recommended_next_step = case health_status when 'pass' then 'allow_paper_autonomous_allocation_proposal_history_review' when 'watch' then 'throttle_paper_autonomous_allocation_proposal_history_review' when 'blocked' then 'block_paper_autonomous_allocation_proposal_history_review' end),
    check (history_report_count >= 0),
    check (pass_report_count >= 0),
    check (watch_report_count >= 0),
    check (blocked_report_count >= 0),
    check (history_report_count = pass_report_count + watch_report_count + blocked_report_count),
    check (latest_history_status is null or latest_history_status in ('pass', 'watch', 'blocked')),
    check (latest_proposal_status is null or latest_proposal_status in ('pass', 'watch', 'blocked')),
    check (latest_allocated_count is null or latest_allocated_count >= 0),
    check (latest_total_allocated_paper_notional is null or latest_total_allocated_paper_notional >= 0),
    check (max_source_age_seconds is null or max_source_age_seconds >= 0),
    check (latest_source_age_seconds is null or latest_source_age_seconds >= 0),
    check (latest_source_age_seconds is null or max_source_age_seconds is null or latest_source_age_seconds <= max_source_age_seconds),
    check (duplicate_latest_report_generated_at_count >= 0),
    check (jsonb_typeof(reason_code_counts_json) = 'array'),
    check (jsonb_typeof(reason_codes_json) = 'array'),
    check (jsonb_typeof(payload_json) = 'object'),
    check ((history_report_count = 0 and latest_history_status is null and latest_proposal_status is null and latest_allocated_count is null and latest_total_allocated_paper_notional is null and max_source_age_seconds is null and latest_source_age_seconds is null and duplicate_latest_report_generated_at_count = 0 and jsonb_array_length(reason_code_counts_json) = 0) or (history_report_count > 0 and latest_history_status is not null and latest_proposal_status is not null and jsonb_array_length(reason_code_counts_json) > 0)),
    check (payload_json ? 'generated_at' and jsonb_typeof(payload_json -> 'generated_at') = 'string' and (payload_json ->> 'generated_at')::timestamptz = generated_at),
    check (payload_json ? 'config_version' and jsonb_typeof(payload_json -> 'config_version') = 'string' and payload_json ->> 'config_version' = config_version),
    check (payload_json ? 'health_status' and jsonb_typeof(payload_json -> 'health_status') = 'string' and payload_json ->> 'health_status' = health_status),
    check (payload_json ? 'recommended_next_step' and jsonb_typeof(payload_json -> 'recommended_next_step') = 'string' and payload_json ->> 'recommended_next_step' = recommended_next_step),
    check (payload_json ? 'history_report_count' and jsonb_typeof(payload_json -> 'history_report_count') = 'number' and (payload_json ->> 'history_report_count')::integer = history_report_count),
    check (payload_json ? 'pass_report_count' and jsonb_typeof(payload_json -> 'pass_report_count') = 'number' and (payload_json ->> 'pass_report_count')::integer = pass_report_count),
    check (payload_json ? 'watch_report_count' and jsonb_typeof(payload_json -> 'watch_report_count') = 'number' and (payload_json ->> 'watch_report_count')::integer = watch_report_count),
    check (payload_json ? 'blocked_report_count' and jsonb_typeof(payload_json -> 'blocked_report_count') = 'number' and (payload_json ->> 'blocked_report_count')::integer = blocked_report_count),
    check (payload_json ? 'latest_history_status' and ((payload_json -> 'latest_history_status' = 'null'::jsonb and latest_history_status is null) or (jsonb_typeof(payload_json -> 'latest_history_status') = 'string' and payload_json ->> 'latest_history_status' = latest_history_status))),
    check (payload_json ? 'latest_proposal_status' and ((payload_json -> 'latest_proposal_status' = 'null'::jsonb and latest_proposal_status is null) or (jsonb_typeof(payload_json -> 'latest_proposal_status') = 'string' and payload_json ->> 'latest_proposal_status' = latest_proposal_status))),
    check (payload_json ? 'latest_allocated_count' and ((payload_json -> 'latest_allocated_count' = 'null'::jsonb and latest_allocated_count is null) or (jsonb_typeof(payload_json -> 'latest_allocated_count') = 'number' and (payload_json ->> 'latest_allocated_count')::integer = latest_allocated_count))),
    check (payload_json ? 'latest_total_allocated_paper_notional' and ((payload_json -> 'latest_total_allocated_paper_notional' = 'null'::jsonb and latest_total_allocated_paper_notional is null) or (jsonb_typeof(payload_json -> 'latest_total_allocated_paper_notional') = 'string' and (payload_json ->> 'latest_total_allocated_paper_notional')::numeric = latest_total_allocated_paper_notional))),
    check (payload_json ? 'max_source_age_seconds' and ((payload_json -> 'max_source_age_seconds' = 'null'::jsonb and max_source_age_seconds is null) or (jsonb_typeof(payload_json -> 'max_source_age_seconds') = 'number' and (payload_json ->> 'max_source_age_seconds')::integer = max_source_age_seconds))),
    check (payload_json ? 'latest_source_age_seconds' and ((payload_json -> 'latest_source_age_seconds' = 'null'::jsonb and latest_source_age_seconds is null) or (jsonb_typeof(payload_json -> 'latest_source_age_seconds') = 'number' and (payload_json ->> 'latest_source_age_seconds')::integer = latest_source_age_seconds))),
    check (payload_json ? 'duplicate_latest_report_generated_at_count' and jsonb_typeof(payload_json -> 'duplicate_latest_report_generated_at_count') = 'number' and (payload_json ->> 'duplicate_latest_report_generated_at_count')::integer = duplicate_latest_report_generated_at_count),
    check (payload_json ? 'reason_code_counts' and jsonb_typeof(payload_json -> 'reason_code_counts') = 'array' and payload_json -> 'reason_code_counts' = reason_code_counts_json),
    check (payload_json ? 'reason_codes' and jsonb_typeof(payload_json -> 'reason_codes') = 'array' and payload_json -> 'reason_codes' = reason_codes_json),
    check (payload_json ? 'paper_only' and payload_json -> 'paper_only' = 'true'::jsonb),
    check (payload_json ? 'report_only' and payload_json -> 'report_only' = 'true'::jsonb),
    check (payload_json ? 'readonly' and payload_json -> 'readonly' = 'true'::jsonb),
    check (paper_only is true),
    check (report_only is true),
    check (readonly is true)
);

create index if not exists idx_paapdhhr_generated_at on public.paper_autonomous_allocation_proposal_db_history_health_reports (generated_at desc);
create index if not exists idx_paapdhhr_config_generated on public.paper_autonomous_allocation_proposal_db_history_health_reports (config_version, generated_at desc);
create index if not exists idx_paapdhhr_health_status_generated on public.paper_autonomous_allocation_proposal_db_history_health_reports (health_status, generated_at desc);
create index if not exists idx_paapdhhr_latest_history_status_generated on public.paper_autonomous_allocation_proposal_db_history_health_reports (latest_history_status, generated_at desc);
create index if not exists idx_paapdhhr_reason_code_counts_json on public.paper_autonomous_allocation_proposal_db_history_health_reports using gin (reason_code_counts_json jsonb_path_ops);
create index if not exists idx_paapdhhr_reason_codes_json on public.paper_autonomous_allocation_proposal_db_history_health_reports using gin (reason_codes_json jsonb_path_ops);
create index if not exists idx_paapdhhr_payload_json on public.paper_autonomous_allocation_proposal_db_history_health_reports using gin (payload_json jsonb_path_ops);
