CREATE TABLE IF NOT EXISTS public.team_profiles (
    team_id text PRIMARY KEY,
    display_name text NOT NULL,
    primary_categories jsonb NOT NULL,
    agent_roles jsonb NOT NULL,
    paper_only boolean NOT NULL DEFAULT true,
    report_only boolean NOT NULL DEFAULT true,
    readonly boolean NOT NULL DEFAULT true,
    inserted_at timestamptz NOT NULL DEFAULT now(),
    CHECK (team_id <> ''),
    CHECK (display_name <> ''),
    CHECK (jsonb_typeof(primary_categories) = 'array'),
    CHECK (jsonb_array_length(primary_categories) > 0),
    CHECK (jsonb_typeof(agent_roles) = 'array'),
    CHECK (jsonb_array_length(agent_roles) > 0),
    CHECK (paper_only IS true),
    CHECK (report_only IS true),
    CHECK (readonly IS true)
);

CREATE TABLE IF NOT EXISTS public.team_market_routes (
    payload_sha256 text PRIMARY KEY,
    generated_at timestamptz NOT NULL,
    team_id text NOT NULL,
    market_slug text NOT NULL,
    config_version text NOT NULL,
    condition_id text NOT NULL,
    category_id text NOT NULL,
    event_template text NOT NULL,
    routing_confidence numeric NOT NULL,
    payload_json jsonb NOT NULL,
    paper_only boolean NOT NULL DEFAULT true,
    report_only boolean NOT NULL DEFAULT true,
    readonly boolean NOT NULL DEFAULT true,
    inserted_at timestamptz NOT NULL DEFAULT now(),
    CHECK (payload_sha256 ~ '^[a-f0-9]{64}$'),
    CHECK (team_id <> ''),
    CHECK (market_slug <> ''),
    CHECK (config_version <> ''),
    CHECK (condition_id <> ''),
    CHECK (category_id <> ''),
    CHECK (event_template <> ''),
    CHECK (routing_confidence >= 0 AND routing_confidence <= 1),
    CHECK (jsonb_typeof(payload_json) = 'object'),
    CHECK ((payload_json ->> 'paper_only') = 'true'),
    CHECK ((payload_json ->> 'report_only') = 'true'),
    CHECK ((payload_json ->> 'readonly') = 'true'),
    CHECK (paper_only IS true),
    CHECK (report_only IS true),
    CHECK (readonly IS true)
);

CREATE TABLE IF NOT EXISTS public.team_forecasts (
    payload_sha256 text PRIMARY KEY,
    generated_at timestamptz NOT NULL,
    forecast_id text NOT NULL,
    condition_id text NOT NULL,
    team_id text NOT NULL,
    market_slug text NOT NULL,
    config_version text NOT NULL,
    selected_side text NOT NULL,
    forecast_probability numeric NOT NULL,
    confidence numeric NOT NULL,
    payload_json jsonb NOT NULL,
    paper_only boolean NOT NULL DEFAULT true,
    report_only boolean NOT NULL DEFAULT true,
    readonly boolean NOT NULL DEFAULT true,
    inserted_at timestamptz NOT NULL DEFAULT now(),
    CHECK (payload_sha256 ~ '^[a-f0-9]{64}$'),
    CHECK (forecast_id <> ''),
    CHECK (condition_id <> ''),
    CHECK (team_id <> ''),
    CHECK (market_slug <> ''),
    CHECK (config_version <> ''),
    CHECK (selected_side IN ('yes', 'no')),
    CHECK (forecast_probability >= 0 AND forecast_probability <= 1),
    CHECK (confidence >= 0 AND confidence <= 1),
    CHECK (jsonb_typeof(payload_json) = 'object'),
    CHECK ((payload_json ->> 'paper_only') = 'true'),
    CHECK ((payload_json ->> 'report_only') = 'true'),
    CHECK ((payload_json ->> 'readonly') = 'true'),
    CHECK (paper_only IS true),
    CHECK (report_only IS true),
    CHECK (readonly IS true)
);

CREATE TABLE IF NOT EXISTS public.team_forecast_evidence (
    payload_sha256 text PRIMARY KEY,
    generated_at timestamptz NOT NULL,
    forecast_id text NOT NULL,
    evidence_id text NOT NULL,
    team_id text NOT NULL,
    market_slug text NOT NULL,
    config_version text NOT NULL,
    source_id text NOT NULL,
    data_timestamp timestamptz NOT NULL,
    data_freshness_seconds integer NOT NULL,
    evidence_type text NOT NULL,
    weight numeric NOT NULL,
    payload_json jsonb NOT NULL,
    paper_only boolean NOT NULL DEFAULT true,
    report_only boolean NOT NULL DEFAULT true,
    readonly boolean NOT NULL DEFAULT true,
    inserted_at timestamptz NOT NULL DEFAULT now(),
    CHECK (payload_sha256 ~ '^[a-f0-9]{64}$'),
    CHECK (forecast_id <> ''),
    CHECK (evidence_id <> ''),
    CHECK (team_id <> ''),
    CHECK (market_slug <> ''),
    CHECK (config_version <> ''),
    CHECK (source_id <> ''),
    CHECK (data_freshness_seconds >= 0),
    CHECK (evidence_type <> ''),
    CHECK (weight >= 0 AND weight <= 1),
    CHECK (jsonb_typeof(payload_json) = 'object'),
    CHECK ((payload_json ->> 'paper_only') = 'true'),
    CHECK ((payload_json ->> 'report_only') = 'true'),
    CHECK ((payload_json ->> 'readonly') = 'true'),
    CHECK (paper_only IS true),
    CHECK (report_only IS true),
    CHECK (readonly IS true)
);

CREATE TABLE IF NOT EXISTS public.team_forecast_outcomes (
    payload_sha256 text NOT NULL UNIQUE,
    generated_at timestamptz NOT NULL,
    outcome_id text PRIMARY KEY,
    forecast_id text NOT NULL,
    team_id text NOT NULL,
    market_slug text NOT NULL,
    config_version text NOT NULL,
    resolved_at timestamptz NOT NULL,
    actual_outcome text NOT NULL,
    forecast_error numeric NOT NULL,
    brier_score numeric NOT NULL,
    paper_pnl numeric NOT NULL,
    cost_adjusted_return numeric NOT NULL,
    directionally_correct boolean NOT NULL,
    profitable_after_cost boolean NOT NULL,
    resolution_dispute_flag boolean NOT NULL,
    payload_json jsonb NOT NULL,
    paper_only boolean NOT NULL DEFAULT true,
    report_only boolean NOT NULL DEFAULT true,
    readonly boolean NOT NULL DEFAULT true,
    inserted_at timestamptz NOT NULL DEFAULT now(),
    CHECK (payload_sha256 ~ '^[a-f0-9]{64}$'),
    CHECK (outcome_id <> ''),
    CHECK (forecast_id <> ''),
    CHECK (team_id <> ''),
    CHECK (market_slug <> ''),
    CHECK (config_version <> ''),
    CHECK (actual_outcome IN ('yes', 'no')),
    CHECK (forecast_error >= 0),
    CHECK (brier_score >= 0),
    CHECK (jsonb_typeof(payload_json) = 'object'),
    CHECK ((payload_json ->> 'paper_only') = 'true'),
    CHECK ((payload_json ->> 'report_only') = 'true'),
    CHECK ((payload_json ->> 'readonly') = 'true'),
    CHECK (paper_only IS true),
    CHECK (report_only IS true),
    CHECK (readonly IS true)
);

CREATE INDEX IF NOT EXISTS idx_team_forecasts_load
    ON public.team_forecasts (team_id, market_slug, generated_at DESC, inserted_at DESC, payload_sha256 DESC);

CREATE INDEX IF NOT EXISTS idx_team_forecast_evidence_load
    ON public.team_forecast_evidence (forecast_id, team_id, market_slug, generated_at DESC, inserted_at DESC, payload_sha256 DESC);

CREATE INDEX IF NOT EXISTS idx_team_forecast_outcomes_load
    ON public.team_forecast_outcomes (team_id, market_slug, resolved_at DESC, generated_at DESC, inserted_at DESC, outcome_id DESC);
